# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build for MacOS
      run: GOOS=darwin GOARCH=arm64 go build -o ebayCalcMac

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o ebayCalcLinux
      
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o ebayCalcWin.exe
      
    - name: Upload MacOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ebayCalcMac
        path: ebayCalcMac

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: ebayCalcLinux
        path: ebayCalcLinux

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: ebayCalcWin
        path: ebayCalcWin.exe
