# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build for MacOS
      run: GOOS=darwin GOARCH=arm64 go build -o ebayCalcMac

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o ebayCalcLinux
      
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o ebayCalcWin.exe

    - name: Create Release and Upload Assets
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG="v0.0.1-${{ github.sha }}"
        gh release create "$TAG" --title "Release $TAG" --notes "Automated build" --draft || true
        
        gh release upload "$TAG" ebayCalcMac --clobber
        gh release upload "$TAG" ebayCalcLinux --clobber
        gh release upload "$TAG" ebayCalcWin.exe --clobber
        
        gh release edit "$TAG" --draft=false
